resources:
  - namespace.yaml
  - rbac.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - ../../services/demo-api/manifests/base

namespace: tenant-b

labels:
  - pairs:
      tenant: tenant-b
    includeSelectors: true

images:
  - name: ghcr.io/rfar/platform-guardrails-lab/demo-api
    newTag: 0.1.0

patches:
  - path: patch-env.yaml
