apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
spec:
  template:
    spec:
      containers:
        - name: demo-api
          env:
            - name: TENANT
              value: tenant-b

