grafana:
  enabled: true
  adminPassword: admin
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard

alertmanager:
  enabled: false

prometheusOperator:
  enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
