apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-api-tenant-a
  namespace: observability
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - tenant-a
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-api
  endpoints:
    - port: http
      path: /metrics
      interval: 5s
